#!/bin/sh

# post-receive                                       Copyright 2018 cPanel, Inc.
#                                                           All rights reserved.
# copyright@cpanel.net                                         http://cpanel.net
# This code is subject to the cPanel license. Unauthorized copying is prohibited

#------------ orijinal ---------
branch=$(/usr/local/cpanel/3rdparty/bin/git branch | awk '$1 == "*"{print $2}')
while read oldrev newrev ref
do
 if [ "x$ref" == "xrefs/heads/$branch" ]
 then
   echo "Recieved update on checked-out branch, queueing deployment."
   (cd .. ; /usr/bin/uapi VersionControlDeployment create repository_root=$PWD)
 fi
done < /dev/stdin
#------------ orijinal ---------


# while read oldrev newrev ref
# do
#   branch=`echo $ref | cut -d/ -f3`

#   if [ "main" == "$branch" ]; then
#     git --work-tree=/home/irispartner/public_html checkout -f $branch
#     echo 'Changes pushed live.'
#   fi

#   if [ "main" == "$branch" ]; then
#     git --work-tree=/home/irispartner/repositories/irispartner checkout -f $branch
#     echo 'Changes pushed to main.'
#   fi
# done

# Taken from: http://blog.ekynoxe.com/2011/10/22/git-post-receive-for-multiple-remote-branches-and-work-trees/
# https://gist.github.com/benfrain/6897792
